CREATE DATABASE IF NOT EXISTS COMISARIA;
USE COMISARIA;

CREATE TABLE VEHICULO (
    matricula VARCHAR(7),
    marca VARCHAR(64),
    modelo VARCHAR(64),
    tipo VARCHAR(64),
    anyo INT,

    CONSTRAINT PK_VEHICULO PRIMARY KEY (matricula)
);

CREATE TABLE DEPARTAMENTO (
    id INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(128),
    telefono VARCHAR(16),
    direccion VARCHAR(128),

    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (id)
);

ALTER TABLE DEPARTAMENTO AUTO_INCREMENT = 100;

CREATE TABLE CIUDADANO (
    dni VARCHAR(9),
    nombre VARCHAR(128),
    direccion VARCHAR(128),
    telefono VARCHAR(16),

    CONSTRAINT PK_CIUDADANO PRIMARY KEY (dni)
);

CREATE TABLE CASO (
    numCaso INT UNSIGNED AUTO_INCREMENT,
    descripcionCaso VARCHAR(1024),
    tipoCaso VARCHAR(64),
    fApertura DATE DEFAULT CURRENT_DATE,
    estadoCaso VARCHAR(32),

    CONSTRAINT PK_CASO PRIMARY KEY (numCaso)
);

CREATE TABLE TESTIGO (
    dni VARCHAR(9),
    
    CONSTRAINT PK_TESTIGO PRIMARY KEY (dni), 
    CONSTRAINT FK_TES_CIU FOREIGN KEY (dni) REFERENCES CIUDADANO(dni) ON DELETE CASCADE
);

CREATE TABLE INVOLUCRAR_T (
    dniTestigo VARCHAR(9),
    numCaso INT UNSIGNED,
    declaracion VARCHAR(512),

    CONSTRAINT PK_INVT PRIMARY KEY (dniTestigo, numCaso),
    CONSTRAINT FK_INVT_TES FOREIGN KEY (dniTestigo) REFERENCES TESTIGO(dni) ON DELETE CASCADE,
    CONSTRAINT FK_INVT_CAS FOREIGN KEY (numCaso) REFERENCES CASO (numCaso) ON DELETE CASCADE
);

CREATE TABLE VICTIMA (
    dni VARCHAR(9),

    CONSTRAINT PK_VICTIMA PRIMARY KEY (dni),
    CONSTRAINT FK_VIC_CIU FOREIGN KEY (dni) REFERENCES CIUDADANO(dni) ON DELETE CASCADE
);

CREATE TABLE INVOLUCRAR_V (
    dniVictima VARCHAR(9),
    numCaso INT UNSIGNED,
    testimonio VARCHAR(512),

    CONSTRAINT PK_INVV PRIMARY KEY (dniVictima, numCaso),
    CONSTRAINT FK_INVV_VIC FOREIGN KEY (dniVictima) REFERENCES VICTIMA(dni) ON DELETE CASCADE,
    CONSTRAINT FK_INVV_CAS FOREIGN KEY (numCaso) REFERENCES CASO (numCaso) ON DELETE CASCADE
);    

CREATE TABLE SOSPECHOSO (
    dni VARCHAR(9),
    
    CONSTRAINT PK_SOSPECHOSO PRIMARY KEY (dni),
    CONSTRAINT FK_SOS_CIU FOREIGN KEY (dni) REFERENCES CIUDADANO(dni) ON DELETE CASCADE
);

CREATE TABLE INVOLUCRAR_S (
    dniSospechoso VARCHAR(9),
    numCaso INT UNSIGNED,
    antecedentes VARCHAR(512),

    CONSTRAINT PK_INVS PRIMARY KEY (dniSospechoso, numCaso),
    CONSTRAINT FK_INVS_SOS FOREIGN KEY (dniSospechoso) REFERENCES SOSPECHOSO(dni) ON DELETE CASCADE,
    CONSTRAINT FK_INVS_CAS FOREIGN KEY (numCaso) REFERENCES CASO (numCaso) ON DELETE CASCADE

);
    
CREATE TABLE AGENTE (
    numPlaca VARCHAR(16),
    nombre VARCHAR(128),
    fnac DATE,
    telefono VARCHAR(16),
    rango VARCHAR(64),
    matriculaVehiculo VARCHAR(7),
    idDepartamento INT UNSIGNED,

    CONSTRAINT PK_AGENTE PRIMARY KEY (numPlaca),
    CONSTRAINT FK_AGENTE_DEPARTAMENTO FOREIGN KEY (idDepartamento) REFERENCES DEPARTAMENTO(id),
    CONSTRAINT FK_AGENTE_VEHICULO FOREIGN KEY (matriculaVehiculo) REFERENCES VEHICULO(matricula)
);

CREATE TABLE INVESTIGAR (
    numPlaca VARCHAR(16),
    numCaso INT UNSIGNED,

    CONSTRAINT PK_INVESTIGAR PRIMARY KEY (numPlaca, numCaso),
    CONSTRAINT FK_INV_AGE FOREIGN KEY (numPlaca) REFERENCES AGENTE(numPlaca) ON DELETE CASCADE,
    CONSTRAINT FK_INV_CAS FOREIGN KEY (numCaso) REFERENCES CASO(numCaso) ON DELETE CASCADE
);

CREATE TABLE EVIDENCIA (
    id INT UNSIGNED AUTO_INCREMENT,
    numCaso INT UNSIGNED NOT NULL,
    descripcion VARCHAR(512),
    tipo VARCHAR(64),

    CONSTRAINT PK_EVIDENCIA PRIMARY KEY (id),
    CONSTRAINT FK_EVI_CAS FOREIGN KEY (numCaso) REFERENCES CASO(numCaso) ON DELETE CASCADE
);
